name : Node application


on : 
  push :
    branches:
      - main


jobs :

  runs-on: ubuntu-latest
  
  test:

  strategy:
    matrix:
      node-version : [20,22]


  steps :

    - uses : actions/checkout@v4

    - uses : actions/setup-node@v4
      with : 
      node-version : ${{matrix.node-version}}


    - run : node --version

    - run : npm i
      working-directory : ./backend
  